[2023-09-02T21:57:14.896+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.tsk4 manual__2023-09-02T21:57:02.065002+00:00 [queued]>
[2023-09-02T21:57:14.911+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.tsk4 manual__2023-09-02T21:57:02.065002+00:00 [queued]>
[2023-09-02T21:57:14.912+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T21:57:14.913+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-02T21:57:14.913+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T21:57:14.933+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2023-09-02 21:57:02.065002+00:00
[2023-09-02T21:57:14.939+0000] {standard_task_runner.py:55} INFO - Started process 1118 to run task
[2023-09-02T21:57:14.943+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dagemail', 'tsk4', 'manual__2023-09-02T21:57:02.065002+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/dagemail.py', '--cfg-path', '/tmp/tmp8185feli']
[2023-09-02T21:57:14.944+0000] {standard_task_runner.py:83} INFO - Job 245: Subtask tsk4
[2023-09-02T21:57:15.029+0000] {task_command.py:388} INFO - Running <TaskInstance: dagemail.tsk4 manual__2023-09-02T21:57:02.065002+00:00 [running]> on host 8d5456a88302
[2023-09-02T21:57:15.108+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=tiagolinhares051@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dagemail
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2023-09-02T21:57:02.065002+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-02T21:57:02.065002+00:00
[2023-09-02T21:57:15.109+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-02T21:57:15.110+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-02T21:57:15.121+0000] {subprocess.py:86} INFO - Output:
[2023-09-02T21:57:15.123+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-02T21:57:15.133+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-02T21:57:15.138+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dagemail, task_id=tsk4, execution_date=20230902T215702, start_date=20230902T215714, end_date=20230902T215715
[2023-09-02T21:57:15.151+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 245 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 1118)
[2023-09-02T21:57:15.194+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-02T21:57:15.217+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
