[2023-09-02T22:08:45.792+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.tsk4 manual__2023-09-02T22:08:32.762713+00:00 [queued]>
[2023-09-02T22:08:45.803+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.tsk4 manual__2023-09-02T22:08:32.762713+00:00 [queued]>
[2023-09-02T22:08:45.803+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T22:08:45.804+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-02T22:08:45.804+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T22:08:45.819+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2023-09-02 22:08:32.762713+00:00
[2023-09-02T22:08:45.824+0000] {standard_task_runner.py:55} INFO - Started process 1834 to run task
[2023-09-02T22:08:45.828+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dagemail', 'tsk4', 'manual__2023-09-02T22:08:32.762713+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/dagemail.py', '--cfg-path', '/tmp/tmpowmbtqwi']
[2023-09-02T22:08:45.829+0000] {standard_task_runner.py:83} INFO - Job 250: Subtask tsk4
[2023-09-02T22:08:45.893+0000] {task_command.py:388} INFO - Running <TaskInstance: dagemail.tsk4 manual__2023-09-02T22:08:32.762713+00:00 [running]> on host 8d5456a88302
[2023-09-02T22:08:45.966+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=eternoaprendiz015@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dagemail
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2023-09-02T22:08:32.762713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-02T22:08:32.762713+00:00
[2023-09-02T22:08:45.967+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-02T22:08:45.968+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-02T22:08:45.980+0000] {subprocess.py:86} INFO - Output:
[2023-09-02T22:08:45.982+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-02T22:08:45.993+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-02T22:08:45.997+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dagemail, task_id=tsk4, execution_date=20230902T220832, start_date=20230902T220845, end_date=20230902T220845
[2023-09-02T22:08:46.012+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 250 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 1834)
[2023-09-02T22:08:46.039+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-02T22:08:46.063+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
